### ISSUE TITLE
Document Support of exports

### ISSUE THREAD

**Issue by csvn** [shellscape/prettier-plugin-package#16]
### Feature Use Case

Support sorting of the [`exports`](https://nodejs.org/api/packages.html#packages_exports) keyword, which is more flexible, while at the same time restricting imports to internal modules.

### Feature Proposal

Sort `exports` close/next to `main`, as they both relate to the package entry points.

**Comment by shellscape** [comment]
Does #15 cover what you're proposing? Or are you asking for it to immediately follow `main`?

**Comment by csvn** [comment]
Yep! You're right, I didn't know it was supported since I only read the README, and did not inspect the code. Thanks @shellscape !

**Comment by shellscape** [comment]
That's a good point though. I haven't been diligent in getting people to update the README with their additions. Thanks for the reminder, I'll get that updated before the next version.
