### ISSUE TITLE
Support // comments in the package.json's script section

### ISSUE THREAD

**Issue by maxpatiiuk** [shellscape/prettier-plugin-package#21]
### Expected Behavior / Situation

As suggested in https://stackoverflow.com/questions/14221579/how-do-i-add-comments-to-package-json-for-npm-install, in the scripts section of package.json, comments can be added like the following:

```
{
    "scripts": {
    "//": "Some global comment",
    "//commandA": "Some comment specifically for commandA",
    "commandA": "some command",
    "//commandB": "Some comment specifically for commandB",
    "commandB": "node --loader ts-node/esm lib/localization/utils/pull.js",
  },
}
```

Thus, the optimal sort order in this case is to have comments right above the line they are commenting

### Actual Behavior / Situation

This plugin sorts all scripts, and puts all comments at the top of the block, resulting in this:

```
{
    "scripts": {
    "//": "Some global comment",
    "//commandA": "Some comment specifically for commandA",
    "//commandB": "Some comment specifically for commandB",
    "commandA": "some command",
    "commandB": "node --loader ts-node/esm lib/localization/utils/pull.js",
  },
}
```

### Modification Proposal

- Detect comments for a script and put the comment right before the script
- OR if that is too tricky, disable sorting in cases when "scripts" section includes comments

### Concerns

There is no single agreed-upon way for providing comments in package json, and this is just one of the suggestions.

**Comment by shellscape** [comment]
Thanks for the issue. To me, the output in the "actual" section is correct. As you're aware, there's no concept of commenting  in JSON, and what is happening here is annotating property names with an indicator that means something to you or your team. You could use any arbitrary character there. Even with this `npm run "//commandA"` will still run (*last time I checked), so it's not actually commented out.

I get what you're after here, but I'd prefer to avoid custom logic for portions of property names. I'm sure that's not the answer you were looking, but this plugin is opinionated. Please feel free to fork.

**Comment by maxpatiiuk** [comment]
Makes sense. No problem
