### ISSUE TITLE
Move keywords at the (very?) bottom, and "module" just after "main"

### ISSUE THREAD

**Issue by tunnckoCore** [shellscape/prettier-plugin-package#6]
Why? Because there are a ton more important stuff to be at the top, like `main`, `module`, `scripts`, and all the `*dependencies`

### Expected Behavior / Situation

Best would be the most important fields to be in similar order. Especially in monorepo setups.

```
engines
main
module
files
scripts
dependencies
devDependencies
peerDependencies
```

It's insane to need to scroll down in your editor or even in the github ui, to see dependencies and etc.

### Actual Behavior / Situation

Not optimal. The `keywords` field is before all the dependencies fields which forces you to scroll to see the deps. And not only that. It just doesn't make much sense to mess in front of your eyes around your most important things. You put them once (usually when creating the module) and forget about them. Or at least you are not touching them that much as like the most of the other fields.

### Modification Proposal

Suggested in "Expected" section.

---

None of the package.json plugins offer good and MEANINGFUL ordering that make sense.

**Comment by shellscape** [comment]
> An opinionated package.json formatter plugin for Prettier

> None of the package.json plugins offer good and MEANINGFUL ordering that make sense.

When something is marked as opinionated, it's important to bear that in mind. Always appreciate feedback and suggestions, but this goes against what I feel is the best ordering. 

> It's insane to need to scroll down in your editor or even in the github ui, to see dependencies and etc.

This verbiage is definitely _not appreciated_. If you can't refrain from using this kind with my personal projects, please refrain from opening new issues.

**Comment by tunnckoCore** [comment]
Sorry, don't take it hard, not meant to offense in anyway.

At least consider the keywords move? That's the most bothering thing. Don't seeing what's the value so unimportant thing to sit at the top?

**Comment by shellscape** [comment]
Unfortunately I'm very happy with the current ordering.  It may be unimportant to you, but I don't share that opinion. There are several forks of this where users have modified the ordering, and I'd encourage you to do the same if the ordering is rubbing you the wrong way. I created this package because the others were not performing how I wanted.
